### ISSUE TITLE
Modelling of a frame

### ISSUE THREAD

**Issue by Beberger** [compas-dev/compas_fea#124]
Hello everyone,

For my master's thesis i am implementing some new features for compas FEA. For the verification i need to model a frame-structure consiting of two walls and a deck over it. The properties of the walls and the deck are not the same. 

![grafik](https://user-images.githubusercontent.com/92813196/149121862-4cf07a13-02a0-4984-aa3c-0b2dcf8619b6.png)

Running this file with compas FEA the deck's displacements seems only to be restrained by the wall's corners and not continiously.

![grafik](https://user-images.githubusercontent.com/92813196/149122788-1af04fa8-73d0-4809-b3e4-b25dd2871b44.png)

Is there a way to model this correctly?

Best regards!
Ben

**Comment by franaudo** [comment]
Hello! - Could you please share the script you wrote to generate this frame?

**Comment by Beberger** [comment]
Thank you very much for the model it works perfectly at my place aswell.
Is there a special command/way to bring those points togheter?  I tried to do that at my model and it didn't work...

**Comment by franaudo** [comment]
One thing you can do is to `weld` the meshes in Rhino. I think you can set the tolerance or something like that and it should move the points together. 

In general, you can avoid this problem if you discretize the elements using the same min length: check [this example](https://compas.dev/compas_fea/latest/examples/mesh_discretise_blender.html) to see how to discretize a rhino object using `compas_fea` .

I will close this issue now, but feel free to reopen it or to open a new one if you encounter a problem with the discretization.

Ciao,
F
