### ISSUE TITLE
loads porpagation in Abaqus

### ISSUE THREAD

**Issue by nefelogeta** [compas-dev/compas_fea#92]
In abaqus the loads from a previous step by default are propagated to the next one. To change the default behavior it is possible to add the key word `OP=NEW` to the step definition. `OP` can take the value `NEW` or `MOD`. 

it should work like this:
- `OP=MOD` is default and implies that the loads applied to different nodes in previous steps are kept.
- `OP=NEW` implies that the loads applied in previous steps are removed.

This applies only to the same type of load: for example, specifying OP=NEW for a concentrated force will not delete the gravity load (I am not sure about this, I will check...)

More info [here](https://www.sharcnet.ca/Software/Abaqus610/Documentation/docs/v6.10/books/gsk/default.htm?startat=ch11s01.html)

**Comment by andrewtliew** [comment]
Altered the **GeneralStep** object to have the ``.modify`` attribute (more appropriate than ``.propagate``). If this is ``True`` (default) then ``OP=MOD``, if ``False`` it switches to ``OP=NEW``.
